{
  "swagger": "2.0",
  "info": {
    "version": "2017-03-01",
    "title": "ApiManagementClient",
    "description": "Use these REST APIs to get the analytics reports associated with your Azure API Management deployment."
  },
  "host": "management.azure.com",
  "schemes": [
    "https"
  ],
  "security": [
    {
      "azure_auth": [
        "user_impersonation"
      ]
    }
  ],
  "securityDefinitions": {
    "azure_auth": {
      "type": "oauth2",
      "authorizationUrl": "https://login.microsoftonline.com/common/oauth2/authorize",
      "flow": "implicit",
      "description": "Azure Active Directory OAuth2 Flow.",
      "scopes": {
        "user_impersonation": "impersonate your user account"
      }
    }
  },
  "paths": {
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/{byApiId}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "operationId": "Reports_ListByApi",
        "description": "Lists report records.",
        "x-ms-examples": {
          "ApiManagementGetReportsByApi": {
            "parameters": {
              "serviceName": "apimService1",
              "resourceGroupName": "rg1",
              "api-version": "2017-03-01",
              "subscriptionId": "subid",
              "byApiId": "byApi",
              "$filter": "timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "name": "Echo API",
                      "apiId": "/apis/5600b59475ff190048040001",
                      "callCountSuccess": 0,
                      "callCountBlocked": 0,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 0,
                      "bandwidth": 0,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 0,
                      "apiTimeMin": 0,
                      "apiTimeMax": 0,
                      "serviceTimeAvg": 0,
                      "serviceTimeMin": 0,
                      "serviceTimeMax": 0
                    },
                    {
                      "name": "httpbin",
                      "apiId": "/apis/57a03a13e4bbd5119c8b19e9",
                      "callCountSuccess": 13,
                      "callCountBlocked": 1,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 14,
                      "bandwidth": 11019,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 1015.7607923076923,
                      "apiTimeMin": 330.3206,
                      "apiTimeMax": 1819.2173,
                      "serviceTimeAvg": 957.094776923077,
                      "serviceTimeMin": 215.24,
                      "serviceTimeMax": 1697.3612
                    }
                  ],
                  "count": 2,
                  "nextLink": ""
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/ResourceGroupNameParameter"
          },
          {
            "$ref": "#/parameters/ServiceNameParameter"
          },
          {
            "name": "byApiId",
            "in": "path",
            "required": true,
            "type": "string",
            "enum": [
              "byApi"
            ],
            "description": "The identifier of the byApi Reports.",
            "x-ms-enum": {
              "modelAsString": true,
              "name": "ByApiIdName"
            }
          },
          {
            "name": "$filter",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "The filter to apply on the operation."
          },
          {
            "$ref": "#/parameters/TopQueryParameter"
          },
          {
            "$ref": "#/parameters/SkipQueryParameter"
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "Lists a collection of Report record.",
            "schema": {
              "$ref": "#/definitions/ReportCollection"
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        },
        "x-ms-odata": "#/definitions/ReportRecordContract",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ]
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/{byUserId}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "operationId": "Reports_ListByUser",
        "description": "Lists report records by User.",
        "x-ms-examples": {
          "ApiManagementGetReportsByUser": {
            "parameters": {
              "serviceName": "apimService1",
              "resourceGroupName": "rg1",
              "api-version": "2017-03-01",
              "subscriptionId": "subid",
              "byUserId": "byUser",
              "$filter": "timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "name": "Administrator",
                      "userId": "/users/1",
                      "callCountSuccess": 13,
                      "callCountBlocked": 1,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 14,
                      "bandwidth": 11019,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 1015.7607923076923,
                      "apiTimeMin": 330.3206,
                      "apiTimeMax": 1819.2173,
                      "serviceTimeAvg": 957.094776923077,
                      "serviceTimeMin": 215.24,
                      "serviceTimeMax": 1697.3612
                    },
                    {
                      "name": "Samir Solanki",
                      "userId": "/users/56eaec62baf08b06e46d27fd",
                      "callCountSuccess": 0,
                      "callCountBlocked": 0,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 0,
                      "bandwidth": 0,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 0,
                      "apiTimeMin": 0,
                      "apiTimeMax": 0,
                      "serviceTimeAvg": 0,
                      "serviceTimeMin": 0,
                      "serviceTimeMax": 0
                    },
                    {
                      "name": "Anonymous",
                      "userId": "/users/54c800b332965a0035030000",
                      "callCountSuccess": 0,
                      "callCountBlocked": 0,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 0,
                      "bandwidth": 0,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 0,
                      "apiTimeMin": 0,
                      "apiTimeMax": 0,
                      "serviceTimeAvg": 0,
                      "serviceTimeMin": 0,
                      "serviceTimeMax": 0
                    }
                  ],
                  "count": 3,
                  "nextLink": ""
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/ResourceGroupNameParameter"
          },
          {
            "$ref": "#/parameters/ServiceNameParameter"
          },
          {
            "name": "byUserId",
            "in": "path",
            "required": true,
            "type": "string",
            "enum": [
              "byUser"
            ],
            "description": "The identifier of the byUser Reports.",
            "x-ms-enum": {
              "modelAsString": true,
              "name": "byUserIdName"
            }
          },
          {
            "name": "$filter",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "The filter to apply on the operation."
          },
          {
            "$ref": "#/parameters/TopQueryParameter"
          },
          {
            "$ref": "#/parameters/SkipQueryParameter"
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "Lists a collection of Report record.",
            "schema": {
              "$ref": "#/definitions/ReportCollection"
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        },
        "x-ms-odata": "#/definitions/ReportRecordContract",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ]
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/{byOperationId}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "operationId": "Reports_ListByOperation",
        "description": "Lists report records by API Operations.",
        "x-ms-examples": {
          "ApiManagementGetReportsByOperation": {
            "parameters": {
              "serviceName": "apimService1",
              "resourceGroupName": "rg1",
              "api-version": "2017-03-01",
              "subscriptionId": "subid",
              "byOperationId": "byOperation",
              "$filter": "timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "name": "get",
                      "apiId": "/apis/57a03a13e4bbd5119c8b19e9",
                      "operationId": "/apis/57a03a13e4bbd5119c8b19e9/operations/57a03a1dd8d14f0a780d7d14",
                      "callCountSuccess": 13,
                      "callCountBlocked": 1,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 14,
                      "bandwidth": 11019,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 1015.7607923076923,
                      "apiTimeMin": 330.3206,
                      "apiTimeMax": 1819.2173,
                      "serviceTimeAvg": 957.094776923077,
                      "serviceTimeMin": 215.24,
                      "serviceTimeMax": 1697.3612
                    },
                    {
                      "name": "GetWeatherInformation",
                      "apiId": "/apis/57c999d1e4bbd50c988cb2c3",
                      "operationId": "/apis/57c999d1e4bbd50c988cb2c3/operations/57c999d1e4bbd50df889c93e",
                      "callCountSuccess": 0,
                      "callCountBlocked": 0,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 0,
                      "bandwidth": 0,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 0,
                      "apiTimeMin": 0,
                      "apiTimeMax": 0,
                      "serviceTimeAvg": 0,
                      "serviceTimeMin": 0,
                      "serviceTimeMax": 0
                    },
                    {
                      "name": "GetCityForecastByZIP",
                      "apiId": "/apis/57c999d1e4bbd50c988cb2c3",
                      "operationId": "/apis/57c999d1e4bbd50c988cb2c3/operations/57c999d1e4bbd50df889c93f",
                      "callCountSuccess": 0,
                      "callCountBlocked": 0,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 0,
                      "bandwidth": 0,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 0,
                      "apiTimeMin": 0,
                      "apiTimeMax": 0,
                      "serviceTimeAvg": 0,
                      "serviceTimeMin": 0,
                      "serviceTimeMax": 0
                    }
                  ],
                  "count": 3,
                  "nextLink": ""
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/ResourceGroupNameParameter"
          },
          {
            "$ref": "#/parameters/ServiceNameParameter"
          },
          {
            "name": "byOperationId",
            "in": "path",
            "required": true,
            "type": "string",
            "enum": [
              "byOperation"
            ],
            "description": "The identifier of the byOperations Reports.",
            "x-ms-enum": {
              "modelAsString": true,
              "name": "byOperationIdName"
            }
          },
          {
            "name": "$filter",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "The filter to apply on the operation."
          },
          {
            "$ref": "#/parameters/TopQueryParameter"
          },
          {
            "$ref": "#/parameters/SkipQueryParameter"
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "Lists a collection of Report record.",
            "schema": {
              "$ref": "#/definitions/ReportCollection"
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        },
        "x-ms-odata": "#/definitions/ReportRecordContract",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ]
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/{byProductId}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "operationId": "Reports_ListByProduct",
        "description": "Lists report records by Product.",
        "x-ms-examples": {
          "ApiManagementGetReportsByProduct": {
            "parameters": {
              "serviceName": "apimService1",
              "resourceGroupName": "rg1",
              "api-version": "2017-03-01",
              "subscriptionId": "subid",
              "byProductId": "byProduct",
              "$filter": "timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "name": "Starter",
                      "productId": "/products/5600b59475ff190048060001",
                      "callCountSuccess": 0,
                      "callCountBlocked": 0,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 0,
                      "bandwidth": 0,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 0,
                      "apiTimeMin": 0,
                      "apiTimeMax": 0,
                      "serviceTimeAvg": 0,
                      "serviceTimeMin": 0,
                      "serviceTimeMax": 0
                    },
                    {
                      "name": "Unlimited",
                      "productId": "/products/5600b59475ff190048060002",
                      "callCountSuccess": 13,
                      "callCountBlocked": 1,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 14,
                      "bandwidth": 11019,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 1015.7607923076923,
                      "apiTimeMin": 330.3206,
                      "apiTimeMax": 1819.2173,
                      "serviceTimeAvg": 957.094776923077,
                      "serviceTimeMin": 215.24,
                      "serviceTimeMax": 1697.3612
                    }
                  ],
                  "count": 2,
                  "nextLink": ""
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/ResourceGroupNameParameter"
          },
          {
            "$ref": "#/parameters/ServiceNameParameter"
          },
          {
            "name": "byProductId",
            "in": "path",
            "required": true,
            "type": "string",
            "enum": [
              "byProduct"
            ],
            "description": "The identifier of the byProduct Reports.",
            "x-ms-enum": {
              "modelAsString": true,
              "name": "byProductIdName"
            }
          },
          {
            "name": "$filter",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "The filter to apply on the operation."
          },
          {
            "$ref": "#/parameters/TopQueryParameter"
          },
          {
            "$ref": "#/parameters/SkipQueryParameter"
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "Lists a collection of Report record.",
            "schema": {
              "$ref": "#/definitions/ReportCollection"
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        },
        "x-ms-odata": "#/definitions/ReportRecordContract",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ]
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/{byGeoId}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "operationId": "Reports_ListByGeo",
        "description": "Lists report records by GeoGraphy.",
        "x-ms-examples": {
          "ApiManagementGetReportsByGeo": {
            "parameters": {
              "serviceName": "apimService1",
              "resourceGroupName": "rg1",
              "api-version": "2017-03-01",
              "subscriptionId": "subid",
              "byGeoId": "byGeo",
              "$filter": "timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "country": "US",
                      "region": "WA",
                      "zip": "98052",
                      "callCountSuccess": 13,
                      "callCountBlocked": 1,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 14,
                      "bandwidth": 11019,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 1015.7607923076923,
                      "apiTimeMin": 330.3206,
                      "apiTimeMax": 1819.2173,
                      "serviceTimeAvg": 957.094776923077,
                      "serviceTimeMin": 215.24,
                      "serviceTimeMax": 1697.3612
                    }
                  ],
                  "count": 1,
                  "nextLink": ""
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/ResourceGroupNameParameter"
          },
          {
            "$ref": "#/parameters/ServiceNameParameter"
          },
          {
            "name": "byGeoId",
            "in": "path",
            "required": true,
            "type": "string",
            "enum": [
              "byGeo"
            ],
            "description": "The identifier of the byGeo Reports.",
            "x-ms-enum": {
              "modelAsString": true,
              "name": "byGeoIdName"
            }
          },
          {
            "name": "$filter",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "The filter to apply on the operation."
          },
          {
            "$ref": "#/parameters/TopQueryParameter"
          },
          {
            "$ref": "#/parameters/SkipQueryParameter"
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "Lists a collection of Report record.",
            "schema": {
              "$ref": "#/definitions/ReportCollection"
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        },
        "x-ms-odata": "#/definitions/ReportRecordContract",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ]
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/{bySubscriptionId}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "operationId": "Reports_ListBySubscription",
        "description": "Lists report records by subscription.",
        "x-ms-examples": {
          "ApiManagementGetReportsBySubscription": {
            "parameters": {
              "serviceName": "apimService1",
              "resourceGroupName": "rg1",
              "api-version": "2017-03-01",
              "subscriptionId": "subid",
              "bySubscriptionId": "bySubscription",
              "$filter": "timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "name": "",
                      "userId": "/users/1",
                      "productId": "/products/5600b59475ff190048060001",
                      "subscriptionId": "/subscriptions/5600b59475ff190048070001",
                      "callCountSuccess": 0,
                      "callCountBlocked": 0,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 0,
                      "bandwidth": 0,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 0,
                      "apiTimeMin": 0,
                      "apiTimeMax": 0,
                      "serviceTimeAvg": 0,
                      "serviceTimeMin": 0,
                      "serviceTimeMax": 0
                    },
                    {
                      "name": "",
                      "userId": "/users/1",
                      "productId": "/products/5600b59475ff190048060002",
                      "subscriptionId": "/subscriptions/5600b59475ff190048070002",
                      "callCountSuccess": 13,
                      "callCountBlocked": 1,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 14,
                      "bandwidth": 11019,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 1015.7607923076923,
                      "apiTimeMin": 330.3206,
                      "apiTimeMax": 1819.2173,
                      "serviceTimeAvg": 957.094776923077,
                      "serviceTimeMin": 215.24,
                      "serviceTimeMax": 1697.3612
                    },
                    {
                      "name": "",
                      "userId": "/users/1",
                      "productId": "/products/5702e97e5157a50f48dce801",
                      "subscriptionId": "/subscriptions/5702e97e5157a50a9c733303",
                      "callCountSuccess": 0,
                      "callCountBlocked": 0,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 0,
                      "bandwidth": 0,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 0,
                      "apiTimeMin": 0,
                      "apiTimeMax": 0,
                      "serviceTimeAvg": 0,
                      "serviceTimeMin": 0,
                      "serviceTimeMax": 0
                    }
                  ],
                  "count": 3,
                  "nextLink": ""
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/ResourceGroupNameParameter"
          },
          {
            "$ref": "#/parameters/ServiceNameParameter"
          },
          {
            "name": "bySubscriptionId",
            "in": "path",
            "required": true,
            "type": "string",
            "enum": [
              "bySubscription"
            ],
            "description": "The identifier of the bySubscription Reports.",
            "x-ms-enum": {
              "modelAsString": true,
              "name": "bySubscriptionIdName"
            }
          },
          {
            "name": "$filter",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "The filter to apply on the operation."
          },
          {
            "$ref": "#/parameters/TopQueryParameter"
          },
          {
            "$ref": "#/parameters/SkipQueryParameter"
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "Lists a collection of Report record.",
            "schema": {
              "$ref": "#/definitions/ReportCollection"
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        },
        "x-ms-odata": "#/definitions/ReportRecordContract",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ]
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/{byTimeId}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "operationId": "Reports_ListByTime",
        "description": "Lists report records by Time.",
        "x-ms-examples": {
          "ApiManagementGetReportsByTime": {
            "parameters": {
              "serviceName": "apimService1",
              "resourceGroupName": "rg1",
              "api-version": "2017-03-01",
              "subscriptionId": "subid",
              "byTimeId": "byTime",
              "$filter": "timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'",
              "interval": "PT15M"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "timestamp": "2017-06-03T00:15:00Z",
                      "interval": "PT15M",
                      "callCountSuccess": 4,
                      "callCountBlocked": 0,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 4,
                      "bandwidth": 3243,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 1337.46335,
                      "apiTimeMin": 885.08390000000009,
                      "apiTimeMax": 1819.2173,
                      "serviceTimeAvg": 1255.917425,
                      "serviceTimeMin": 882.8264,
                      "serviceTimeMax": 1697.3612
                    },
                    {
                      "timestamp": "2017-06-03T00:30:00Z",
                      "interval": "PT15M",
                      "callCountSuccess": 9,
                      "callCountBlocked": 1,
                      "callCountFailed": 0,
                      "callCountOther": 0,
                      "callCountTotal": 10,
                      "bandwidth": 7776,
                      "cacheHitCount": 0,
                      "cacheMissCount": 0,
                      "apiTimeAvg": 872.78187777777782,
                      "apiTimeMin": 330.3206,
                      "apiTimeMax": 1093.8407,
                      "serviceTimeAvg": 824.28471111111116,
                      "serviceTimeMin": 215.24,
                      "serviceTimeMax": 973.22620000000006
                    }
                  ],
                  "count": 2,
                  "nextLink": ""
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/ResourceGroupNameParameter"
          },
          {
            "$ref": "#/parameters/ServiceNameParameter"
          },
          {
            "name": "byTimeId",
            "in": "path",
            "required": true,
            "type": "string",
            "enum": [
              "byTime"
            ],
            "description": "The identifier of the byTime Reports.",
            "x-ms-enum": {
              "modelAsString": true,
              "name": "byTimeIdName"
            }
          },
          {
            "name": "$filter",
            "in": "query",
            "required": false,
            "type": "string",
            "description": "The filter to apply on the operation."
          },
          {
            "$ref": "#/parameters/TopQueryParameter"
          },
          {
            "$ref": "#/parameters/SkipQueryParameter"
          },
          {
            "name": "interval",
            "in": "query",
            "required": true,
            "type": "string",
            "format": "duration",
            "description": "By time interval. Interval must be multiple of 15 minutes and may not be zero. The value should be in ISO  8601 format (http://en.wikipedia.org/wiki/ISO_8601#Durations).This code can be used to convert TimeSpan to a valid interval string: XmlConvert.ToString(new TimeSpan(hours, minutes, secconds))"
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "Lists a collection of Report record.",
            "schema": {
              "$ref": "#/definitions/ReportCollection"
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": "nextLink"
        },
        "x-ms-odata": "#/definitions/ReportRecordContract",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ]
      }
    },
    "/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ApiManagement/service/{serviceName}/reports/{byRequestId}": {
      "get": {
        "tags": [
          "Reports"
        ],
        "operationId": "Reports_ListByRequest",
        "description": "Lists report records by Request.",
        "x-ms-examples": {
          "ApiManagementGetReportsByRequest": {
            "parameters": {
              "serviceName": "apimService1",
              "resourceGroupName": "rg1",
              "api-version": "2017-03-01",
              "subscriptionId": "subid",
              "byRequestId": "byRequest",
              "$filter": "timestamp ge datetime'2017-06-01T00:00:00' and timestamp le datetime'2017-06-04T00:00:00'"
            },
            "responses": {
              "200": {
                "body": {
                  "value": [
                    {
                      "apiId": "/apis/5931a75ae4bbd512a88c680b",
                      "operationId": "/apis/5931a75ae4bbd512a88c680b/operations/-",
                      "productId": "/products/-",
                      "userId": "/users/1",
                      "method": "GET",
                      "url": "https://apimService1.azure-api.net/echo/resource?param1=sample",
                      "ipAddress": "207.xx.155.xx",
                      "responseCode": 404,
                      "responseSize": 405,
                      "timestamp": "2017-06-03T00:17:00.1649134Z",
                      "cache": "none",
                      "apiTime": 221.1544,
                      "serviceTime": 0,
                      "apiRegion": "East Asia",
                      "subscriptionId": "/subscriptions/5600b59475ff190048070002",
                      "requestId": "63e7119c-26aa-433c-96d7-f6f3267ff52f",
                      "requestSize": 0
                    },
                    {
                      "apiId": "/apis/5931a75ae4bbd512a88c680b",
                      "operationId": "/apis/5931a75ae4bbd512a88c680b/operations/-",
                      "productId": "/products/-",
                      "userId": "/users/1",
                      "method": "POST",
                      "url": "https://apimService1.azure-api.net/echo/resource",
                      "ipAddress": "207.xx.155.xx",
                      "responseCode": 404,
                      "responseSize": 403,
                      "timestamp": "2017-06-03T00:17:20.5255131Z",
                      "cache": "none",
                      "apiTime": 6.6754000000000007,
                      "serviceTime": 0,
                      "apiRegion": "East Asia",
                      "subscriptionId": "/subscriptions/5600b59475ff190048070002",
                      "requestId": "e581b7f7-c9ec-4fc6-8ab9-3855d9b00b04",
                      "requestSize": 0
                    }
                  ],
                  "count": 2
                }
              }
            }
          }
        },
        "parameters": [
          {
            "$ref": "#/parameters/ResourceGroupNameParameter"
          },
          {
            "$ref": "#/parameters/ServiceNameParameter"
          },
          {
            "name": "byRequestId",
            "in": "path",
            "required": true,
            "type": "string",
            "enum": [
              "byRequest"
            ],
            "description": "The identifier of the byRequest Reports.",
            "x-ms-enum": {
              "modelAsString": true,
              "name": "byRequestIdName"
            }
          },
          {
            "name": "$filter",
            "in": "query",
            "required": true,
            "type": "string",
            "description": "The filter to apply on the operation."
          },
          {
            "$ref": "#/parameters/TopQueryParameter"
          },
          {
            "$ref": "#/parameters/SkipQueryParameter"
          },
          {
            "$ref": "#/parameters/ApiVersionParameter"
          },
          {
            "$ref": "#/parameters/SubscriptionIdParameter"
          }
        ],
        "responses": {
          "200": {
            "description": "Lists a collection of Report record.",
            "schema": {
              "$ref": "#/definitions/RequestReportCollection"
            }
          }
        },
        "x-ms-pageable": {
          "nextLinkName": null
        },
        "x-ms-odata": "#/definitions/RequestReportRecordContract",
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ]
      }
    }
  },
  "definitions": {
    "ReportCollection": {
      "properties": {
        "value": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ReportRecordContract"
          },
          "description": "Page values."
        },
        "count": {
          "type": "integer",
          "format": "int64",
          "description": "Total record count number across all pages."
        },
        "nextLink": {
          "type": "string",
          "description": "Next page link if any."
        }
      },
      "description": "Paged Report records list representation."
    },
    "ReportRecordContract": {
      "properties": {
        "name": {
          "type": "string",
          "description": "Name depending on report endpoint specifies product, API, operation or developer name."
        },
        "timestamp": {
          "type": "string",
          "format": "date-time",
          "description": "Start of aggregation period. The date conforms to the following format: `yyyy-MM-ddTHH:mm:ssZ` as specified by the ISO 8601 standard.\n"
        },
        "interval": {
          "type": "string",
          "description": "Length of agregation period.  Interval must be multiple of 15 minutes and may not be zero. The value should be in ISO 8601 format (http://en.wikipedia.org/wiki/ISO_8601#Durations)."
        },
        "country": {
          "type": "string",
          "description": "Country to which this record data is related."
        },
        "region": {
          "type": "string",
          "description": "Country region to which this record data is related."
        },
        "zip": {
          "type": "string",
          "description": "Zip code to which this record data is related."
        },
        "userId": {
          "readOnly": true,
          "type": "string",
          "description": "User identifier path. /users/{userId}"
        },
        "productId": {
          "readOnly": true,
          "type": "string",
          "description": "Product identifier path. /products/{productId}"
        },
        "apiId": {
          "type": "string",
          "description": "API identifier path. /apis/{apiId}"
        },
        "operationId": {
          "type": "string",
          "description": "Operation identifier path. /apis/{apiId}/operations/{operationId}"
        },
        "apiRegion": {
          "type": "string",
          "description": "API region identifier."
        },
        "subscriptionId": {
          "type": "string",
          "description": "Subscription identifier path. /subscriptions/{subscriptionId}"
        },
        "callCountSuccess": {
          "type": "integer",
          "format": "int32",
          "description": "Number of succesful calls. This includes calls returning HttpStatusCode <= 301 and HttpStatusCode.NotModified and HttpStatusCode.TemporaryRedirect"
        },
        "callCountBlocked": {
          "type": "integer",
          "format": "int32",
          "description": "Number of calls blocked due to invalid credentials. This includes calls returning HttpStatusCode.Unauthorize and HttpStatusCode.Forbidden and HttpStatusCode.TooManyRequests"
        },
        "callCountFailed": {
          "type": "integer",
          "format": "int32",
          "description": "Number of calls failed due to proxy or backend errors. This includes calls returning HttpStatusCode.BadRequest(400) and any Code between HttpStatusCode.InternalServerError (500) and 600"
        },
        "callCountOther": {
          "type": "integer",
          "format": "int32",
          "description": "Number of other calls."
        },
        "callCountTotal": {
          "type": "integer",
          "format": "int32",
          "description": "Total number of calls."
        },
        "bandwidth": {
          "type": "integer",
          "format": "int64",
          "description": "Bandwidth consumed."
        },
        "cacheHitCount": {
          "type": "integer",
          "format": "int32",
          "description": "Number of times when content was served from cache policy."
        },
        "cacheMissCount": {
          "type": "integer",
          "format": "int32",
          "description": "Number of times content was fetched from backend."
        },
        "apiTimeAvg": {
          "type": "number",
          "format": "double",
          "description": "Average time it took to process request."
        },
        "apiTimeMin": {
          "type": "number",
          "format": "double",
          "description": "Minimum time it took to process request."
        },
        "apiTimeMax": {
          "type": "number",
          "format": "double",
          "description": "Maximum time it took to process request."
        },
        "serviceTimeAvg": {
          "type": "number",
          "format": "double",
          "description": "Average time it took to process request on backend."
        },
        "serviceTimeMin": {
          "type": "number",
          "format": "double",
          "description": "Minimum time it took to process request on backend."
        },
        "serviceTimeMax": {
          "type": "number",
          "format": "double",
          "description": "Maximum time it took to process request on backend."
        }
      },
      "description": "Report data."
    },
    "RequestReportCollection": {
      "properties": {
        "value": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/RequestReportRecordContract"
          },
          "description": "Page values."
        },
        "count": {
          "type": "integer",
          "format": "int64",
          "description": "Total record count number across all pages."
        }
      },
      "description": "Paged Report records list representation."
    },
    "RequestReportRecordContract": {
      "properties": {
        "apiId": {
          "type": "string",
          "description": "API identifier path. /apis/{apiId}"
        },
        "operationId": {
          "type": "string",
          "description": "Operation identifier path. /apis/{apiId}/operations/{operationId}"
        },
        "productId": {
          "readOnly": true,
          "type": "string",
          "description": "Product identifier path. /products/{productId}"
        },
        "userId": {
          "readOnly": true,
          "type": "string",
          "description": "User identifier path. /users/{userId}"
        },
        "method": {
          "type": "string",
          "description": "The HTTP method associated with this request.."
        },
        "url": {
          "type": "string",
          "description": "The full URL associated with this request."
        },
        "ipAddress": {
          "type": "string",
          "description": "The client IP address associated with this request."
        },
        "backendResponseCode": {
          "type": "string",
          "description": "The HTTP status code received by the gateway as a result of forwarding this request to the backend."
        },
        "responseCode": {
          "type": "integer",
          "format": "int32",
          "description": "The HTTP status code returned by the gateway."
        },
        "responseSize": {
          "type": "integer",
          "format": "int32",
          "description": "The size of the response returned by the gateway."
        },
        "timestamp": {
          "type": "string",
          "format": "date-time",
          "description": "The date and time when this request was received by the gateway in ISO 8601 format."
        },
        "cache": {
          "type": "string",
          "description": "Specifies if response cache was involved in generating the response. If the value is none, the cache was not used. If the value is hit, cached response was returned. If the value is miss, the cache was used but lookup resulted in a miss and request was fullfilled by the backend."
        },
        "apiTime": {
          "type": "number",
          "format": "double",
          "description": "The total time it took to process this request."
        },
        "serviceTime": {
          "type": "number",
          "format": "double",
          "description": "he time it took to forward this request to the backend and get the response back."
        },
        "apiRegion": {
          "type": "string",
          "description": "Azure region where the gateway that processed this request is located."
        },
        "subscriptionId": {
          "type": "string",
          "description": "Subscription identifier path. /subscriptions/{subscriptionId}"
        },
        "requestId": {
          "type": "string",
          "description": "Request Identifier."
        },
        "requestSize": {
          "type": "integer",
          "format": "int32",
          "description": "The size of this request.."
        }
      },
      "description": "Request Report data."
    }
  },
  "parameters": {
    "SubscriptionIdParameter": {
      "name": "subscriptionId",
      "in": "path",
      "required": true,
      "type": "string",
      "description": "Subscription credentials which uniquely identify Microsoft Azure subscription. The subscription ID forms part of the URI for every service call."
    },
    "ApiVersionParameter": {
      "name": "api-version",
      "in": "query",
      "required": true,
      "type": "string",
      "description": "Version of the API to be used with the client request."
    },
    "SkipQueryParameter": {
      "name": "$skip",
      "in": "query",
      "required": false,
      "type": "integer",
      "format": "int32",
      "description": "Number of records to skip.",
      "minimum": 0,
      "x-ms-parameter-location": "method"
    },
    "TopQueryParameter": {
      "name": "$top",
      "in": "query",
      "required": false,
      "type": "integer",
      "format": "int32",
      "description": "Number of records to return.",
      "minimum": 1,
      "x-ms-parameter-location": "method"
    },
    "ServiceNameParameter": {
      "name": "serviceName",
      "in": "path",
      "required": true,
      "type": "string",
      "description": "The name of the API Management service.",
      "minLength": 1,
      "maxLength": 50,
      "pattern": "^[a-zA-Z](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?$",
      "x-ms-parameter-location": "method"
    },
    "ResourceGroupNameParameter": {
      "name": "resourceGroupName",
      "in": "path",
      "required": true,
      "type": "string",
      "description": "The name of the resource group.",
      "x-ms-parameter-location": "method"
    }
  },
  "x-internal-toc-name": "Reports"
}